plugins: 
  - duplicates
  - edit
  - embedart
  - fetchart
  - info
  - lastgenre
  - lyrics
  - musicbrainz
  - permissions
  - the


directory: /home/adaris/data/media/music

library: /home/adaris/db/beets/beetslibrary.db

paths:
    default: %the{$albumartist}/($year) $album/$track $title

ui:
    color: yes

import:
    incremental: yes
    incremental_skip_later: yes
    write: yes
    move: no
    autotag: yes
    bell: yes
    log: /home/adaris/db/beets/beet.log    
    duplicate_action: skip

original_date: yes

per_disc_numbering: yes

musicbrainz:
    host: musicbrainz.org
    https: no
    ratelimit: 1
    ratelimit_interval: 1.0
    search_limit: 5
    external_ids:
        discogs: yes
        bandcamp: yes
        spotify: no
        deezer: no
        beatport: no
        tidal: no

the:
    a: no
